In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df1=pd.read_csv("/content/all_comments.csv")
df1.head()

                                             comment
0  What's up guys.  Eric Kripke here.  Just poppe...
1  The dolphin.  I nearly fell out of my chair wi...
2  I'm a few episodes in and it's insane. Weirdly...
3  Holyshit that plot twist at the end! That is a...
4  The thing that I wanna know the most is what i...

In [ ]:
df2=pd.read_csv("/content/all_comments2.csv")
df3=pd.read_csv("/content/all_comments3.csv")
df4=pd.read_csv("/content/all_comments4.csv")
df5=pd.read_csv("/content/all_comments5.csv")

In [ ]:
#for df in [df2, df3,df4]:
#    if 'Comment' in df.columns:
#        df.rename(columns={'Comment': 'comment'}, inplace=True)

comment_series = [
    df1['comment'],
    df2['comment'],
    df3['comment'],
    df4['comment'],
    df5['comment']
]

all_comments_df = pd.DataFrame(pd.concat(comment_series, ignore_index=True), columns=['comment'])

display(all_comments_df.head())

                                             comment
0  What's up guys.  Eric Kripke here.  Just poppe...
1  The dolphin.  I nearly fell out of my chair wi...
2  I'm a few episodes in and it's insane. Weirdly...
3  Holyshit that plot twist at the end! That is a...
4  The thing that I wanna know the most is what i...

In [ ]:
all_comments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5187 entries, 0 to 5186
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   comment  5187 non-null   object
dtypes: object(1)
memory usage: 40.7+ KB

In [ ]:
all_comments_df.dropna(subset=['comment'], inplace=True)
all_comments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5187 entries, 0 to 5186
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   comment  5187 non-null   object
dtypes: object(1)
memory usage: 40.7+ KB

In [ ]:
all_comments_df.to_csv('all_commentsallseason.csv', index=False)

The `all_comments.csv` file has been saved to your Colab environment. You can download it by clicking on the folder icon on the left panel, navigating to the file, and right-clicking to download.