In [ ]:
import pandas as pd  #Season-1
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/all_comments.csv')
df.head()

                                             comment
0  What's up guys.  Eric Kripke here.  Just poppe...
1  The dolphin.  I nearly fell out of my chair wi...
2  I'm a few episodes in and it's insane. Weirdly...
3  Holyshit that plot twist at the end! That is a...
4  The thing that I wanna know the most is what i...

In [ ]:
import re
from collections import Counter
def clean_text(text):
    text = str(text).lower()

    # remove possessive 's
    text = re.sub(r"'s\b", "", text)

    # remove punctuation
    text = re.sub(r"[^\w\s]", " ", text)

    # remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

df["clean_comment"] = df["comment"].apply(clean_text)
df.head()

,comment,clean_comment
0,What's up guys. Eric Kripke here. Just poppe...,what up guys eric kripke here just popped over...
1,The dolphin. I nearly fell out of my chair wi...,the dolphin i nearly fell out of my chair with...
2,I'm a few episodes in and it's insane. Weirdly...,i m a few episodes in and it insane weirdly al...
3,Holyshit that plot twist at the end! That is a...,holyshit that plot twist at the end that is a ...
4,The thing that I wanna know the most is what i...,the thing that i wanna know the most is what i...

In [ ]:
character_dict = {

    "Homelander": [
        "homelander",
        "antony star",
        "superman"
    ],

    "Billy Butcher": [
        "billy",
        "butcher",
        "billy butcher",
        "karl urban"
    ],

    "Hughie": [
        "hughie",
        "hugh",
        "jack quaid"
    ],

    "Starlight": [
        "starlight",
        "annie",
        "annie january",
        "erin moriarty"
    ],

    "Queen Maeve": [
        "maeve",
        "queen maeve",
        "wonder woman",
        "dominique mcelligott"
    ],

    "A-Train": [
        "atrain",
        "a train",
        "a-train",
        "flash",
        "jessie t usher"
    ],

    "The Deep": [
        "deep",
        "the deep",
        "aquaman",
        "chace crawford"
    ],

    "Black Noir": [
        "black noir",
        "noir",
        "nathan mitchell"
    ],

    "Frenchie": [
        "frenchie",
        "serge",
        "tomer capone"
    ],

    "Kimiko": [
        "kimiko",
        "female",
        "karen fukuhara"
    ],

    "Mother's Milk": [
        "mother milk",
        "mother's milk",
        "mothers milk"
        "mm",
        "marvin t milk",
        "laz alonso"
    ],

    "Stormfront": [
        "stormfront",
        "clara",
        "aya cash"
    ],

    "Soldier Boy": [
        "soldier boy",
        "captain america",
        "jensen ackles"
    ],

    "Ryan": [
        "ryan",
        "cameron crovetti"
    ],
    "Translucent":[
        "translucent",
        "alex hassell"
    ],
    "Madelyn Stillwell":[
        "madelyn stillwell",
        "madelyn",
        "stillwell",
        "elisabeth shue"
    ],
    "Becca Butcher":[
        "becca",
        "shantel vansanten"
    ]
}

In [ ]:
character_count = Counter()

for comment in df["clean_comment"]:

    for character, aliases in character_dict.items():

        for alias in aliases:

            pattern = r"\b" + re.escape(alias) + r"\b"

            if re.search(pattern, comment):

                character_count[character] += 1
                break

In [ ]:
result = (
    pd.DataFrame(
        character_count.items(),
        columns=["Character", "Mention_Count"]
    )
    .sort_values("Mention_Count", ascending=False)
)

display(result)

            Character  Mention_Count
3          Homelander            196
4       Billy Butcher            133
9            The Deep             62
12          Starlight             51
5              Hughie             40
1          Black Noir             39
10            A-Train             37
7              Kimiko             29
14      Becca Butcher             25
6            Frenchie             21
2   Madelyn Stillwell             20
11        Translucent             19
0         Queen Maeve             16
15         Stormfront              5
13        Soldier Boy              5
8       Mother's Milk              4
16               Ryan              1

In [ ]:
import pandas as pd  #Season-2
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/all_comments2.csv')
df.head()

                                             comment
0  It‘s kind of odd that the leader of the church...
1  Will there be enough budget for a robot Nazi n...
2  I was expecting starlight to use stormfront li...
3  I’m a little bummed butcher didn’t get stuck w...
4      "Did I hear you say... Butcher?" Was AMAZING.

In [ ]:
import re
from collections import Counter
def clean_text(text):
    text = str(text).lower()

    # remove possessive 's
    text = re.sub(r"'s\b", "", text)

    # remove punctuation
    text = re.sub(r"[^\w\s]", " ", text)

    # remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

df["clean_comment"] = df["comment"].apply(clean_text)
df.head()

,comment,clean_comment
0,It‘s kind of odd that the leader of the church...,it s kind of odd that the leader of the church...
1,Will there be enough budget for a robot Nazi n...,will there be enough budget for a robot nazi n...
2,I was expecting starlight to use stormfront li...,i was expecting starlight to use stormfront li...
3,I’m a little bummed butcher didn’t get stuck w...,i m a little bummed butcher didn t get stuck w...
4,"""Did I hear you say... Butcher?"" Was AMAZING.",did i hear you say butcher was amazing

In [ ]:
character_dict = {

    "Homelander": [
        "homelander",
        "antony star",
        "superman"
    ],

    "Billy Butcher": [
        "billy",
        "butcher",
        "billy butcher",
        "karl urban"
    ],

    "Hughie": [
        "hughie",
        "hugh",
        "jack quaid"
    ],

    "Starlight": [
        "starlight",
        "annie",
        "annie january",
        "erin moriarty"
    ],

    "Queen Maeve": [
        "maeve",
        "queen maeve",
        "wonder woman",
        "dominique mcelligott"
    ],

    "A-Train": [
        "atrain",
        "a train",
        "a-train",
        "flash",
        "jessie t usher"
    ],

    "The Deep": [
        "deep",
        "the deep",
        "aquaman",
        "chace crawford"
    ],

    "Black Noir": [
        "black noir",
        "noir",
        "nathan mitchell"
    ],

    "Frenchie": [
        "frenchie",
        "serge",
        "tomer capone"
    ],

    "Kimiko": [
        "kimiko",
        "female",
        "karen fukuhara"
    ],

    "Mother's Milk": [
        "mother milk",
        "mother's milk",
        "mothers milk"
        "mm",
        "marvin t milk",
        "laz alonso"
    ],

    "Stormfront": [
        "stormfront",
        "clara",
        "aya cash"
    ],

    "Soldier Boy": [
        "soldier boy",
        "captain america",
        "jensen ackles"
    ],

    "Ryan": [
        "ryan",
        "cameron crovetti"
    ],
    "Translucent":[
        "translucent",
        "alex hassell"
    ],
    "Madelyn Stillwell":[
        "madelyn stillwell",
        "madelyn",
        "stillwell",
        "elisabeth shue"
    ],
    "Becca Butcher":[
        "becca",
        "shantel vansanten"
    ],
    "Ashley Barrett":[
        "ashley",
        "colby minifie"
    ],
    "Victoria Neuman":[
        "neuman",
        "victoria",
        "nadia",
        "claudia doumit"
    ]
}

In [ ]:
character_count = Counter()

for comment in df["clean_comment"]:

    for character, aliases in character_dict.items():

        for alias in aliases:

            pattern = r"\b" + re.escape(alias) + r"\b"

            if re.search(pattern, comment):

                character_count[character] += 1
                break

In [ ]:
result = (
    pd.DataFrame(
        character_count.items(),
        columns=["Character", "Mention_Count"]
    )
    .sort_values("Mention_Count", ascending=False)
)

display(result)

            Character  Mention_Count
6          Homelander            196
2          Stormfront            187
3       Billy Butcher            116
7                Ryan             70
0              Hughie             69
8            The Deep             53
1           Starlight             52
9         Queen Maeve             52
4     Victoria Neuman             50
5       Becca Butcher             40
12             Kimiko             27
13         Black Noir             27
10            A-Train             23
11           Frenchie             15
14     Ashley Barrett              8
15        Soldier Boy              6
16  Madelyn Stillwell              5
18        Translucent              5
17      Mother's Milk              2

In [ ]:
import pandas as pd  #Season-3
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/all_comments3.csv')
df.head()

                                             comment
0  Never thought I'd feel bad watching someone ea...
1  Who else will Homelander compare himself to th...
2  Supersonic (Drummer Boy) sounds genuinely awes...
3  0v,NXqjvGK?7L=n8R3UJYeq%!BN[/{9?F,@{qf&8xt[BrW...
4              I've missed this show so fucking much

In [ ]:
import re
from collections import Counter
def clean_text(text):
    text = str(text).lower()

    # remove possessive 's
    text = re.sub(r"'s\b", "", text)

    # remove punctuation
    text = re.sub(r"[^\w\s]", " ", text)

    # remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

df["clean_comment"] = df["comment"].apply(clean_text)
df.head()

,comment,clean_comment
0,Never thought I'd feel bad watching someone ea...,never thought i d feel bad watching someone ea...
1,Who else will Homelander compare himself to th...,who else will homelander compare himself to th...
2,Supersonic (Drummer Boy) sounds genuinely awes...,supersonic drummer boy sounds genuinely awesom...
3,"0v,NXqjvGK?7L=n8R3UJYeq%!BN[/{9?F,@{qf&8xt[BrW...",0v nxqjvgk 7l n8r3ujyeq bn 9 f qf 8xt brw 5qfx...
4,I've missed this show so fucking much,i ve missed this show so fucking much

In [ ]:
character_dict = {

    "Homelander": [
        "homelander",
        "antony star",
        "superman"
    ],

    "Billy Butcher": [
        "billy",
        "butcher",
        "billy butcher",
        "karl urban"
    ],

    "Hughie": [
        "hughie",
        "hugh",
        "jack quaid"
    ],

    "Starlight": [
        "starlight",
        "annie",
        "annie january",
        "erin moriarty"
    ],

    "Queen Maeve": [
        "maeve",
        "queen maeve",
        "wonder woman",
        "dominique mcelligott"
    ],

    "A-Train": [
        "atrain",
        "a train",
        "a-train",
        "flash",
        "jessie t usher"
    ],

    "The Deep": [
        "deep",
        "the deep",
        "aquaman",
        "chace crawford"
    ],

    "Black Noir": [
        "black noir",
        "noir",
        "nathan mitchell"
    ],

    "Frenchie": [
        "frenchie",
        "serge",
        "tomer capone"
    ],

    "Kimiko": [
        "kimiko",
        "female",
        "karen fukuhara"
    ],

    "Mother's Milk": [
        "mother milk",
        "mother's milk",
        "mothers milk"
        "mm",
        "marvin t milk",
        "laz alonso"
    ],

    "Stormfront": [
        "stormfront",
        "clara",
        "aya cash"
    ],

    "Soldier Boy": [
        "soldier boy",
        "captain america",
        "jensen ackles"
    ],

    "Ryan": [
        "ryan",
        "cameron crovetti"
    ],
    "Translucent":[
        "translucent",
        "alex hassell"
    ],
    "Madelyn Stillwell":[
        "madelyn stillwell",
        "madelyn",
        "stillwell",
        "elisabeth shue"
    ],
    "Becca Butcher":[
        "becca",
        "shantel vansanten"
    ],
    "Ashley Barrett":[
        "ashley",
        "colby minifie"
    ],
    "Victoria Neuman":[
        "neuman",
        "victoria",
        "nadia",
        "claudia doumit"
    ],
    "Stan Edgar":[
        "stan edgar",
        "edgar",
        "stan"
        "stanford edgar",
        "giancarlo esposito"
    ]
}

In [ ]:
character_count = Counter()

for comment in df["clean_comment"]:

    for character, aliases in character_dict.items():

        for alias in aliases:

            pattern = r"\b" + re.escape(alias) + r"\b"

            if re.search(pattern, comment):

                character_count[character] += 1
                break

In [ ]:
result = (
    pd.DataFrame(
        character_count.items(),
        columns=["Character", "Mention_Count"]
    )
    .sort_values("Mention_Count", ascending=False)
)

display(result)

            Character  Mention_Count
1          Homelander            245
3       Billy Butcher            118
8         Soldier Boy            112
7           Starlight             69
13         Black Noir             60
4              Hughie             59
15               Ryan             50
11        Queen Maeve             47
0            The Deep             32
14    Victoria Neuman             29
9          Stan Edgar             28
5            Frenchie             26
12            A-Train             24
10             Kimiko             24
2          Stormfront             20
6      Ashley Barrett             12
18      Becca Butcher              7
16  Madelyn Stillwell              3
17      Mother's Milk              3
19        Translucent              2

In [ ]:
import pandas as pd   #Season-4
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/all_comments4.csv')
df.head()

                                             comment
0  Join the official subreddit Discord server to ...
1       MM just can’t get a break from giant penises
2         What the fuck happened to Ashley Barrett?!
3   I wonder if Kimiko is gonna say more next season
4  Omg they just killed Victoria like she was not...

In [ ]:
import re
from collections import Counter
def clean_text(text):
    text = str(text).lower()

    # remove possessive 's
    text = re.sub(r"'s\b", "", text)

    # remove punctuation
    text = re.sub(r"[^\w\s]", " ", text)

    # remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

df["clean_comment"] = df["comment"].apply(clean_text)
df.head()

,comment,clean_comment
0,Join the official subreddit Discord server to ...,join the official subreddit discord server to ...
1,MM just can’t get a break from giant penises,mm just can t get a break from giant penises
2,What the fuck happened to Ashley Barrett?!,what the fuck happened to ashley barrett
3,I wonder if Kimiko is gonna say more next season,i wonder if kimiko is gonna say more next season
4,Omg they just killed Victoria like she was not...,omg they just killed victoria like she was not...

In [ ]:
character_dict = {

    "Homelander": [
        "homelander",
        "antony star",
        "superman"
    ],

    "Billy Butcher": [
        "billy",
        "butcher",
        "billy butcher",
        "karl urban"
    ],

    "Hughie": [
        "hughie",
        "hugh",
        "jack quaid"
    ],

    "Starlight": [
        "starlight",
        "annie",
        "annie january",
        "erin moriarty"
    ],

    "Queen Maeve": [
        "maeve",
        "queen maeve",
        "wonder woman",
        "dominique mcelligott"
    ],

    "A-Train": [
        "atrain",
        "a train",
        "a-train",
        "flash",
        "jessie t usher"
    ],

    "The Deep": [
        "deep",
        "the deep",
        "aquaman",
        "chace crawford"
    ],

    "Black Noir": [
        "black noir",
        "noir",
        "nathan mitchell"
    ],

    "Frenchie": [
        "frenchie",
        "serge",
        "tomer capone"
    ],

    "Kimiko": [
        "kimiko",
        "female",
        "karen fukuhara"
    ],

    "Mother's Milk": [
        "mother milk",
        "mother's milk",
        "mothers milk"
        "mm",
        "marvin t milk",
        "laz alonso"
    ],

    "Stormfront": [
        "stormfront",
        "clara",
        "aya cash"
    ],

    "Soldier Boy": [
        "soldier boy",
        "captain america",
        "jensen ackles"
    ],

    "Ryan": [
        "ryan",
        "cameron crovetti"
    ],
    "Translucent":[
        "translucent",
        "alex hassell"
    ],
    "Madelyn Stillwell":[
        "madelyn stillwell",
        "madelyn",
        "stillwell",
        "elisabeth shue"
    ],
    "Becca Butcher":[
        "becca",
        "shantel vansanten"
    ],
    "Ashley Barrett":[
        "ashley",
        "colby minifie"
    ],
    "Victoria Neuman":[
        "neuman",
        "victoria",
        "nadia",
        "claudia doumit"
    ],
    "Stan Edgar":[
        "stan edgar",
        "edgar",
        "stan"
        "stanford edgar",
        "giancarlo esposito"
    ],
    "Joe Kessler":[
        "joe kessler",
        "kessler",
        "joe",
        "jeffrey dean morgan"
    ],
    "Sister Sage":[
        "sister sage",
        "sage",
        "jessica bradley"
    ],
    "Firecracker":[
        "firecracker",
        "fire cracker",
        "valorie curry"
    ]
}

In [ ]:
character_count = Counter()

for comment in df["clean_comment"]:

    for character, aliases in character_dict.items():

        for alias in aliases:

            pattern = r"\b" + re.escape(alias) + r"\b"

            if re.search(pattern, comment):

                character_count[character] += 1
                break

In [ ]:
result = (
    pd.DataFrame(
        character_count.items(),
        columns=["Character", "Mention_Count"]
    )
    .sort_values("Mention_Count", ascending=False)
)

display(result)

          Character  Mention_Count
3     Billy Butcher            205
6         Starlight            171
4        Homelander            167
7            Hughie            119
1            Kimiko            115
5              Ryan            112
2   Victoria Neuman             95
0    Ashley Barrett             93
14      Sister Sage             89
8          Frenchie             74
9       Soldier Boy             69
11          A-Train             56
12         The Deep             41
15      Firecracker             33
13       Black Noir             24
10      Joe Kessler             23
16       Stan Edgar             13
18      Queen Maeve             10
19    Becca Butcher              8
17       Stormfront              3
20    Mother's Milk              1

In [ ]:
import pandas as pd  #Season-5
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/all_comments5.csv')
df.head()

                                             comment
0  The Deep yelling "NOOO" When starlight asked h...
1  Gen V gets their series finale exit to gtfo to...
2  Was the Homelander in space nuking earth pictu...
3  At the end, butcher was right. Theyre just goi...
4                                   waiting for ep 9

In [ ]:
import re
from collections import Counter
def clean_text(text):
    text = str(text).lower()

    # remove possessive 's
    text = re.sub(r"'s\b", "", text)

    # remove punctuation
    text = re.sub(r"[^\w\s]", " ", text)

    # remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

df["clean_comment"] = df["comment"].apply(clean_text)
df.head()

,comment,clean_comment
0,"The Deep yelling ""NOOO"" When starlight asked h...",the deep yelling nooo when starlight asked him...
1,Gen V gets their series finale exit to gtfo to...,gen v gets their series finale exit to gtfo to...
2,Was the Homelander in space nuking earth pictu...,was the homelander in space nuking earth pictu...
3,"At the end, butcher was right. Theyre just goi...",at the end butcher was right theyre just going...
4,waiting for ep 9,waiting for ep 9

In [ ]:
character_dict = {

    "Homelander": [
        "homelander",
        "antony star",
        "superman"
    ],

    "Billy Butcher": [
        "billy",
        "butcher",
        "billy butcher",
        "karl urban"
    ],

    "Hughie": [
        "hughie",
        "hugh",
        "jack quaid"
    ],

    "Starlight": [
        "starlight",
        "annie",
        "annie january",
        "erin moriarty"
    ],

    "Queen Maeve": [
        "maeve",
        "queen maeve",
        "wonder woman",
        "dominique mcelligott"
    ],

    "A-Train": [
        "atrain",
        "a train",
        "a-train",
        "flash",
        "jessie t usher"
    ],

    "The Deep": [
        "deep",
        "the deep",
        "aquaman",
        "chace crawford"
    ],

    "Black Noir": [
        "black noir",
        "noir",
        "nathan mitchell"
    ],

    "Frenchie": [
        "frenchie",
        "serge",
        "tomer capone"
    ],

    "Kimiko": [
        "kimiko",
        "female",
        "karen fukuhara"
    ],

    "Mother's Milk": [
        "mother milk",
        "mother's milk",
        "mothers milk",
        "mm",
        "marvin t milk",
        "laz alonso"
    ],

    "Stormfront": [
        "stormfront",
        "clara",
        "aya cash"
    ],

    "Soldier Boy": [
        "soldier boy",
        "captain america",
        "jensen ackles"
    ],

    "Ryan": [
        "ryan",
        "cameron crovetti"
    ],
    "Translucent":[
        "translucent",
        "alex hassell"
    ],
    "Madelyn Stillwell":[
        "madelyn stillwell",
        "madelyn",
        "stillwell",
        "elisabeth shue"
    ],
    "Becca Butcher":[
        "becca",
        "shantel vansanten"
    ],
    "Ashley Barrett":[
        "ashley",
        "colby minifie"
    ],
    "Victoria Neuman":[
        "neuman",
        "victoria",
        "nadia",
        "claudia doumit"
    ],
    "Stan Edgar":[
        "stan edgar",
        "edgar",
        "stan",
        "stanford edgar",
        "giancarlo esposito"
    ],
    "Joe Kessler":[
        "joe kessler",
        "kessler",
        "joe",
        "jeffrey dean morgan"
    ],
    "Sister Sage":[
        "sister sage",
        "sage",
        "jessica bradley"
    ],
    "Firecracker":[
        "firecracker",
        "fire cracker",
        "valorie curry"
    ]
}

In [ ]:
character_count = Counter()

for comment in df["clean_comment"]:

    for character, aliases in character_dict.items():

        for alias in aliases:

            pattern = r"\b" + re.escape(alias) + r"\b"

            if re.search(pattern, comment):

                character_count[character] += 1
                break

In [ ]:
result = (
    pd.DataFrame(
        character_count.items(),
        columns=["Character", "Mention_Count"]
    )
    .sort_values("Mention_Count", ascending=False)
)

display(result)

            Character  Mention_Count
2          Homelander            313
3       Billy Butcher            202
5         Soldier Boy            101
7                Ryan             82
6              Hughie             80
4              Kimiko             75
1            The Deep             73
0           Starlight             61
9            Frenchie             39
13      Mother's Milk             33
10         Stormfront             32
11        Sister Sage             29
14            A-Train             27
12     Ashley Barrett             24
17         Stan Edgar             18
15         Black Noir             16
8         Firecracker             12
18        Queen Maeve              6
16        Joe Kessler              5
19    Victoria Neuman              4
22      Becca Butcher              4
20        Translucent              3
21  Madelyn Stillwell              1

In [ ]:
import pandas as pd #Season 1-5 combine
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/all_commentsallseason.csv')
df.head()

                                             comment
0  What's up guys.  Eric Kripke here.  Just poppe...
1  The dolphin.  I nearly fell out of my chair wi...
2  I'm a few episodes in and it's insane. Weirdly...
3  Holyshit that plot twist at the end! That is a...
4  The thing that I wanna know the most is what i...

In [ ]:
import re
from collections import Counter
def clean_text(text):
    text = str(text).lower()

    # remove possessive 's
    text = re.sub(r"'s\b", "", text)

    # remove punctuation
    text = re.sub(r"[^\w\s]", " ", text)

    # remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

df["clean_comment"] = df["comment"].apply(clean_text)
df.head()

,comment,clean_comment
0,What's up guys. Eric Kripke here. Just poppe...,what up guys eric kripke here just popped over...
1,The dolphin. I nearly fell out of my chair wi...,the dolphin i nearly fell out of my chair with...
2,I'm a few episodes in and it's insane. Weirdly...,i m a few episodes in and it insane weirdly al...
3,Holyshit that plot twist at the end! That is a...,holyshit that plot twist at the end that is a ...
4,The thing that I wanna know the most is what i...,the thing that i wanna know the most is what i...

In [ ]:
character_dict = {

    "Homelander": [
        "homelander",
        "antony star",
        "superman"
    ],

    "Billy Butcher": [
        "billy",
        "butcher",
        "billy butcher",
        "karl urban"
    ],

    "Hughie": [
        "hughie",
        "hugh",
        "jack quaid"
    ],

    "Starlight": [
        "starlight",
        "annie",
        "annie january",
        "erin moriarty"
    ],

    "Queen Maeve": [
        "maeve",
        "queen maeve",
        "wonder woman",
        "dominique mcelligott"
    ],

    "A-Train": [
        "atrain",
        "a train",
        "a-train",
        "flash",
        "jessie t usher"
    ],

    "The Deep": [
        "deep",
        "the deep",
        "aquaman",
        "chace crawford"
    ],

    "Black Noir": [
        "black noir",
        "noir",
        "nathan mitchell"
    ],

    "Frenchie": [
        "frenchie",
        "serge",
        "tomer capone"
    ],

    "Kimiko": [
        "kimiko",
        "female",
        "karen fukuhara"
    ],

    "Mother's Milk": [
        "mother milk",
        "mother's milk",
        "mothers milk",
        "mm",
        "marvin t milk",
        "laz alonso"
    ],

    "Stormfront": [
        "stormfront",
        "clara",
        "aya cash"
    ],

    "Soldier Boy": [
        "soldier boy",
        "captain america",
        "jensen ackles"
    ],

    "Ryan": [
        "ryan",
        "cameron crovetti"
    ],
    "Translucent":[
        "translucent",
        "alex hassell"
    ],
    "Madelyn Stillwell":[
        "madelyn stillwell",
        "madelyn",
        "stillwell",
        "elisabeth shue"
    ],
    "Becca Butcher":[
        "becca",
        "shantel vansanten"
    ],
    "Ashley Barrett":[
        "ashley",
        "colby minifie"
    ],
    "Victoria Neuman":[
        "neuman",
        "victoria",
        "nadia",
        "claudia doumit"
    ],
    "Stan Edgar":[
        "stan edgar",
        "edgar",
        "stan",
        "stanford edgar",
        "giancarlo esposito"
    ],
    "Joe Kessler":[
        "joe kessler",
        "kessler",
        "joe",
        "jeffrey dean morgan"
    ],
    "Sister Sage":[
        "sister sage",
        "sage",
        "jessica bradley"
    ],
    "Firecracker":[
        "firecracker",
        "fire cracker",
        "valorie curry"
    ]
}

In [ ]:
character_count = Counter()

for comment in df["clean_comment"]:

    for character, aliases in character_dict.items():

        for alias in aliases:

            pattern = r"\b" + re.escape(alias) + r"\b"

            if re.search(pattern, comment):

                character_count[character] += 1
                break

In [ ]:
result = (
    pd.DataFrame(
        character_count.items(),
        columns=["Character", "Mention_Count"]
    )
    .sort_values("Mention_Count", ascending=False)
)

display(result)

            Character  Mention_Count
3          Homelander           1117
4       Billy Butcher            774
12          Starlight            404
5              Hughie            367
18               Ryan            315
13        Soldier Boy            293
7              Kimiko            270
9            The Deep            261
15         Stormfront            247
19    Victoria Neuman            178
6            Frenchie            175
10            A-Train            167
1          Black Noir            166
17     Ashley Barrett            138
0         Queen Maeve            131
20        Sister Sage            119
8       Mother's Milk            114
16         Stan Edgar             93
14      Becca Butcher             84
22        Firecracker             45
2   Madelyn Stillwell             29
11        Translucent             29
21        Joe Kessler             28

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5187 entries, 0 to 5186
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   comment        5187 non-null   object
 1   clean_comment  5187 non-null   object
dtypes: object(2)
memory usage: 81.2+ KB

#Character association , Apriori

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/all_commentsallseason.csv')
df.head()

                                             comment
0  What's up guys.  Eric Kripke here.  Just poppe...
1  The dolphin.  I nearly fell out of my chair wi...
2  I'm a few episodes in and it's insane. Weirdly...
3  Holyshit that plot twist at the end! That is a...
4  The thing that I wanna know the most is what i...

In [ ]:
import re
from collections import Counter
def clean_text(text):
    text = str(text).lower()

    # remove possessive 's
    text = re.sub(r"'s\b", "", text)

    # remove punctuation
    text = re.sub(r"[^\w\s]", " ", text)

    # remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

df["clean_comment"] = df["comment"].apply(clean_text)
df.head()

,comment,clean_comment
0,What's up guys. Eric Kripke here. Just poppe...,what up guys eric kripke here just popped over...
1,The dolphin. I nearly fell out of my chair wi...,the dolphin i nearly fell out of my chair with...
2,I'm a few episodes in and it's insane. Weirdly...,i m a few episodes in and it insane weirdly al...
3,Holyshit that plot twist at the end! That is a...,holyshit that plot twist at the end that is a ...
4,The thing that I wanna know the most is what i...,the thing that i wanna know the most is what i...

In [ ]:
character_dict = {

    "Homelander": [
        "homelander",
        "antony star",
        "superman"
    ],

    "Billy Butcher": [
        "billy",
        "butcher",
        "billy butcher",
        "karl urban"
    ],

    "Hughie": [
        "hughie",
        "hugh",
        "jack quaid"
    ],

    "Starlight": [
        "starlight",
        "annie",
        "annie january",
        "erin moriarty"
    ],

    "Queen Maeve": [
        "maeve",
        "queen maeve",
        "wonder woman",
        "dominique mcelligott"
    ],

    "A-Train": [
        "atrain",
        "a train",
        "a-train",
        "flash",
        "jessie t usher"
    ],

    "The Deep": [
        "deep",
        "the deep",
        "aquaman",
        "chace crawford"
    ],

    "Black Noir": [
        "black noir",
        "noir",
        "nathan mitchell"
    ],

    "Frenchie": [
        "frenchie",
        "serge",
        "tomer capone"
    ],

    "Kimiko": [
        "kimiko",
        "female",
        "karen fukuhara"
    ],

    "Mother's Milk": [
        "mother milk",
        "mother's milk",
        "mothers milk",
        "mm",
        "marvin t milk",
        "laz alonso"
    ],

    "Stormfront": [
        "stormfront",
        "clara",
        "aya cash"
    ],

    "Soldier Boy": [
        "soldier boy",
        "captain america",
        "jensen ackles"
    ],

    "Ryan": [
        "ryan",
        "cameron crovetti"
    ],
    "Translucent":[
        "translucent",
        "alex hassell"
    ],
    "Madelyn Stillwell":[
        "madelyn stillwell",
        "madelyn",
        "stillwell",
        "elisabeth shue"
    ],
    "Becca Butcher":[
        "becca",
        "shantel vansanten"
    ],
    "Ashley Barrett":[
        "ashley",
        "colby minifie"
    ],
    "Victoria Neuman":[
        "neuman",
        "victoria",
        "nadia",
        "claudia doumit"
    ],
    "Stan Edgar":[
        "stan edgar",
        "edgar",
        "stan",
        "stanford edgar",
        "giancarlo esposito"
    ],
    "Joe Kessler":[
        "joe kessler",
        "kessler",
        "joe",
        "jeffrey dean morgan"
    ],
    "Sister Sage":[
        "sister sage",
        "sage",
        "jessica bradley"
    ],
    "Firecracker":[
        "firecracker",
        "fire cracker",
        "valorie curry"
    ]
}

In [ ]:
import re
import pandas as pd

def extract_characters(comment, character_dict):

    # Convert comment to lowercase
    comment = str(comment).lower()

    found_characters = set()

    for character, aliases in character_dict.items():

        for alias in aliases:

            # lowercase alias
            alias = alias.lower()

            # escape special regex characters
            pattern = r"\b" + re.escape(alias) + r"\b"

            # check whether alias exists
            if re.search(pattern, comment):
                found_characters.add(character)
                break   # move to next character

    return ", ".join(sorted(found_characters))


df["Characters"] = df["clean_comment"].apply(
    lambda x: extract_characters(x, character_dict)
)

In [ ]:
df.head(50)

,comment,clean_comment,Characters
0,What's up guys. Eric Kripke here. Just poppe...,what up guys eric kripke here just popped over...,
1,The dolphin. I nearly fell out of my chair wi...,the dolphin i nearly fell out of my chair with...,
2,I'm a few episodes in and it's insane. Weirdly...,i m a few episodes in and it insane weirdly al...,Queen Maeve
3,Holyshit that plot twist at the end! That is a...,holyshit that plot twist at the end that is a ...,
4,The thing that I wanna know the most is what i...,the thing that i wanna know the most is what i...,Black Noir
5,The scene where Stillwell announces that their...,the scene where stillwell announces that their...,Madelyn Stillwell
6,First few episodes are awesome. Neat take on s...,first few episodes are awesome neat take on su...,
7,I know I get some flack for this but I like ba...,i know i get some flack for this but i like ba...,
8,Really dug the simon pegg cameo.,really dug the simon pegg cameo,
9,Homelander feels like that brightburn kid that...,homelander feels like that brightburn kid that...,Homelander
10,I have read The Boys at least...4 different ti...,i have read the boys at least 4 different time...,"Billy Butcher, Frenchie, Hughie, Kimiko, Mothe..."
11,This was basically ‘Karl Urban Says Cunt: The ...,this was basically karl urban says cunt the sh...,Billy Butcher
12,Haven't read thru the comments so not sure if ...,haven t read thru the comments so not sure if ...,
13,"Frenchie just keeps growing and growing on me,...",frenchie just keeps growing and growing on me ...,Frenchie
14,Well fuck me sideways I never saw that ending ...,well fuck me sideways i never saw that ending ...,
15,Can I just say there hasn't been a poorly cast...,can i just say there hasn t been a poorly cast...,
16,"Can we get an F for Larry the Lobster, I felt ...",can we get an f for larry the lobster i felt that,
17,If you shit talk Karl Urban's accent and say n...,if you shit talk karl urban accent and say not...,Billy Butcher
18,Haley Joel Osmont as a washed up child celebri...,haley joel osmont as a washed up child celebri...,
19,It’s a small detail that doesn’t really affect...,it s a small detail that doesn t really affect...,
20,"Holy shit, this is fantastic. They are getting...",holy shit this is fantastic they are getting i...,"Billy Butcher, Homelander, Hughie"
21,Some of my favorite parts were with Black Noir...,some of my favorite parts were with black noir...,"Black Noir, Homelander"
22,I didn't even hear about this or know it was a...,i didn t even hear about this or know it was a...,Billy Butcher
23,Elizabeth Shue looking like the finest MILF ever!,elizabeth shue looking like the finest milf ever,
24,Is it weird I kinda feel bad for The Deep? I m...,is it weird i kinda feel bad for the deep i me...,The Deep
25,“I’m disappointed in all of you... Except you ...,i m disappointed in all of you except you noir...,Black Noir
26,Lots of really good performances in this show ...,lots of really good performances in this show ...,Homelander
27,Why you gotta be down on my best girl Baby Spi...,why you gotta be down on my best girl baby spi...,Billy Butcher
28,My favorite arc by far was The Deep's. He's so...,my favorite arc by far was the deep he someone...,The Deep
29,They're really giving these characters some de...,they re really giving these characters some de...,Homelander
30,This is literally why I came to this sub today...,this is literally why i came to this sub today...,Homelander
31,I'm a bad boy who LOVES TO EAT ASS,i m a bad boy who loves to eat ass,
32,Every time I heard the train sound effect when...,every time i heard the train sound effect when...,A-Train
33,Whatever happened to Cherie ? Now I realize wh...,whatever happened to cherie now i realize why ...,Frenchie
34,"Just finished the season and wow what a show, ...",just finished the season and wow what a show a...,The Deep
35,Coming in as someone who only really read the ...,coming in as someone who only really read the ...,
36,What with the random flies buzzing around? Is ...,what with the random flies buzzing around is i...,
37,I was surprised Doppelgänger didn't play a big...,i was surprised doppelgänger didn t play a big...,
38,"Wow, for once I'm kind of glad I went into thi...",wow for once i m kind of glad i went into this...,
39,"Urban has to be the next Wolverine, at least f...",urban has to be the next wolverine at least fo...,
40,I'm just curious. It doesn't change my enjoyme...,i m just curious it doesn t change my enjoymen...,Translucent
41,The homelander scene in Syria was so damn good...,the homelander scene in syria was so damn good...,Homelander
42,Watched the whole series in 2 days. Loved it. ...,watched the whole series in 2 days loved it i ...,"Starlight, The Deep"
43,So why did they ditch Jack From Jupiter in exc...,so why did they ditch jack from jupiter in exc...,"Madelyn Stillwell, Translucent"
44,Loved the fact that they got Simon Peg in the ...,loved the fact that they got simon peg in the ...,
45,"Small nitpicking, but they portrayed the CIA l...",small nitpicking but they portrayed the cia li...,
46,"This line ""came three times""",this line came three times,
47,Coming from some one who has never read the co...,coming from some one who has never read the co...,"Black Noir, The Deep"
48,"Okay, what accent is Billy Butcher trying to n...",okay what accent is billy butcher trying to na...,Billy Butcher
49,People need to remember we're only on season 1...,people need to remember we re only on season 1...,

In [ ]:
# Create 0/1 matrix
basket = df["Characters"].str.get_dummies(sep=", ")

# Give each row a comment ID
basket.index = range(1, len(basket) + 1)
basket.index.name = "Comment_ID"

# View the result
basket.head()

,A-Train,Ashley Barrett,Becca Butcher,Billy Butcher,Black Noir,Firecracker,Frenchie,Homelander,Hughie,Joe Kessler,...,Queen Maeve,Ryan,Sister Sage,Soldier Boy,Stan Edgar,Starlight,Stormfront,The Deep,Translucent,Victoria Neuman
Comment_ID,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
basket.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5187 entries, 1 to 5187
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   A-Train            5187 non-null   int64
 1   Ashley Barrett     5187 non-null   int64
 2   Becca Butcher      5187 non-null   int64
 3   Billy Butcher      5187 non-null   int64
 4   Black Noir         5187 non-null   int64
 5   Firecracker        5187 non-null   int64
 6   Frenchie           5187 non-null   int64
 7   Homelander         5187 non-null   int64
 8   Hughie             5187 non-null   int64
 9   Joe Kessler        5187 non-null   int64
 10  Kimiko             5187 non-null   int64
 11  Madelyn Stillwell  5187 non-null   int64
 12  Mother's Milk      5187 non-null   int64
 13  Queen Maeve        5187 non-null   int64
 14  Ryan               5187 non-null   int64
 15  Sister Sage        5187 non-null   int64
 16  Soldier Boy        5187 non-null   int64
 17  Stan Edgar         5187 non-null   int64
 18  Starlight          5187 non-null   int64
 19  Stormfront         5187 non-null   int64
 20  The Deep           5187 non-null   int64
 21  Translucent        5187 non-null   int64
 22  Victoria Neuman    5187 non-null   int64
dtypes: int64(23)
memory usage: 932.2 KB

In [ ]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.12/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2026.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [ ]:
from mlxtend.frequent_patterns import apriori, association_rules

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
frequent_itemsets = apriori(
    basket,
    min_support=0.005,
    use_colnames=True
)

frequent_itemsets

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/mlxtend/frequent_patterns/fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

      support                                           itemsets
0    0.032196                                          (A-Train)
1    0.026605                                   (Ashley Barrett)
2    0.016194                                    (Becca Butcher)
3    0.149219                                    (Billy Butcher)
4    0.032003                                       (Black Noir)
..        ...                                                ...
228  0.005013                  (Hughie, Kimiko, Ryan, Starlight)
229  0.005205  (Hughie, Billy Butcher, Kimiko, Frenchie, Star...
230  0.005398  (Hughie, Homelander, Ryan, Billy Butcher, Kimiko)
231  0.005205  (Hughie, Homelander, Billy Butcher, Kimiko, St...
232  0.005976  (Homelander, Ryan, Billy Butcher, Kimiko, Star...

[233 rows x 2 columns]

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
frequent_itemsets["Comment_Count"] = (
    frequent_itemsets["support"] * len(basket)
).round().astype(int)

frequent_itemsets

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,support,itemsets,Comment_Count
0,0.032196,(A-Train),167
1,0.026605,(Ashley Barrett),138
2,0.016194,(Becca Butcher),84
3,0.149219,(Billy Butcher),774
4,0.032003,(Black Noir),166
...,...,...,...
228,0.005013,"(Hughie, Kimiko, Ryan, Starlight)",26
229,0.005205,"(Hughie, Billy Butcher, Kimiko, Frenchie, Star...",27
230,0.005398,"(Hughie, Homelander, Ryan, Billy Butcher, Kimiko)",28
231,0.005205,"(Hughie, Homelander, Billy Butcher, Kimiko, St...",27
232,0.005976,"(Homelander, Ryan, Billy Butcher, Kimiko, Star...",31

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
frequent_itemsets["Combination_Size"] = (
    frequent_itemsets["itemsets"].apply(len)
)

combinations = frequent_itemsets[
    frequent_itemsets["Combination_Size"] >= 2
].copy()

combinations.sort_values(
    "support",
    ascending=False
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,support,itemsets,Comment_Count,Combination_Size
43,0.064585,"(Billy Butcher, Homelander)",335,2
75,0.032003,"(Homelander, Ryan)",166,2
44,0.031039,"(Hughie, Billy Butcher)",161,2
48,0.031039,"(Billy Butcher, Ryan)",161,2
88,0.030846,"(Hughie, Starlight)",160,2
...,...,...,...,...
135,0.005013,"(Billy Butcher, Homelander, Queen Maeve)",26,3
199,0.005013,"(Ryan, Soldier Boy, Starlight)",26,3
170,0.005013,"(Hughie, Frenchie, Ryan)",26,3
213,0.005013,"(Billy Butcher, Kimiko, Homelander, Soldier Boy)",26,4
228,0.005013,"(Hughie, Kimiko, Ryan, Starlight)",26,4

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
rules = association_rules(
    frequent_itemsets,
    metric="confidence",
    min_threshold=0.10
)

rules.head()

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(A-Train),(Ashley Barrett),0.032196,0.026605,0.005591,0.173653,6.527076,1.0,0.004734,1.177949,0.874962,0.105072,0.151067,0.191899
1,(Ashley Barrett),(A-Train),0.026605,0.032196,0.005591,0.210145,6.527076,1.0,0.004734,1.225293,0.869937,0.105072,0.183869,0.191899
2,(A-Train),(Billy Butcher),0.032196,0.149219,0.010411,0.323353,2.166968,1.0,0.005606,1.257349,0.556441,0.060879,0.204676,0.196560
3,(A-Train),(Homelander),0.032196,0.215346,0.013110,0.407186,1.890843,1.0,0.006176,1.323608,0.486809,0.055921,0.244489,0.234031
4,(A-Train),(Hughie),0.032196,0.070754,0.006169,0.191617,2.708218,1.0,0.003891,1.149512,0.651737,0.063745,0.130066,0.139405

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
rules_sorted = rules.sort_values(
    "lift",
    ascending=False
)

rules_sorted[
    [
        "antecedents",
        "consequents",
        "support",
        "confidence",
        "lift"
    ]
].head(20)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

,antecedents,consequents,support,confidence,lift
868,"(Frenchie, Starlight)","(Hughie, Billy Butcher, Kimiko)",0.005205,0.500000,48.027778
849,"(Hughie, Billy Butcher, Kimiko)","(Frenchie, Starlight)",0.005205,0.500000,48.027778
857,"(Billy Butcher, Frenchie, Starlight)","(Hughie, Kimiko)",0.005205,0.613636,44.207386
860,"(Hughie, Kimiko)","(Billy Butcher, Frenchie, Starlight)",0.005205,0.375000,44.207386
861,"(Hughie, Frenchie)","(Billy Butcher, Kimiko, Starlight)",0.005205,0.450000,40.243966
856,"(Billy Butcher, Kimiko, Starlight)","(Hughie, Frenchie)",0.005205,0.465517,40.243966
782,"(Hughie, Kimiko)","(Frenchie, Starlight)",0.005784,0.416667,40.023148
787,"(Frenchie, Starlight)","(Hughie, Kimiko)",0.005784,0.555556,40.023148
850,"(Hughie, Billy Butcher, Frenchie)","(Kimiko, Starlight)",0.005205,0.613636,39.786648
867,"(Kimiko, Starlight)","(Hughie, Billy Butcher, Frenchie)",0.005205,0.337500,39.786648
853,"(Hughie, Kimiko, Starlight)","(Billy Butcher, Frenchie)",0.005205,0.586957,38.538525
864,"(Billy Butcher, Frenchie)","(Hughie, Kimiko, Starlight)",0.005205,0.341772,38.538525
863,"(Billy Butcher, Kimiko)","(Hughie, Frenchie, Starlight)",0.005205,0.254717,34.768868
854,"(Hughie, Frenchie, Starlight)","(Billy Butcher, Kimiko)",0.005205,0.710526,34.768868
887,"(Hughie, Ryan)","(Billy Butcher, Kimiko, Homelander)",0.005398,0.474576,34.670804
884,"(Billy Butcher, Kimiko, Homelander)","(Hughie, Ryan)",0.005398,0.394366,34.670804
876,"(Hughie, Homelander, Ryan)","(Billy Butcher, Kimiko)",0.005398,0.700000,34.253774
894,"(Billy Butcher, Kimiko)","(Hughie, Homelander, Ryan)",0.005398,0.264151,34.253774
879,"(Hughie, Billy Butcher, Ryan)","(Kimiko, Homelander)",0.005398,0.651163,33.775814
891,"(Kimiko, Homelander)","(Hughie, Billy Butcher, Ryan)",0.005398,0.280000,33.775814

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [ ]:
from mlxtend.frequent_patterns import apriori

# ==========================================
# 1. Find ONLY 2-character combinations
# ==========================================

pair_itemsets = apriori(
    basket,
    min_support=0.005,
    use_colnames=True,
    max_len=2
)

# Keep only pairs
pair_itemsets = pair_itemsets[
    pair_itemsets["itemsets"].apply(len) == 2
].copy()


# ==========================================
# 2. Calculate number of comments
# ==========================================

pair_itemsets["Comment_Count"] = (
    pair_itemsets["support"] * len(basket)
).round().astype(int)


# ==========================================
# 3. Remove very rare pairs
#    Keep pairs appearing in >= 50 comments
# ==========================================

pair_itemsets = pair_itemsets[
    pair_itemsets["Comment_Count"] >= 50
].copy()


# ==========================================
# 4. Calculate LIFT manually
# ==========================================

def calculate_lift(itemset):

    characters = list(itemset)

    char1 = characters[0]
    char2 = characters[1]

    # Probability of character 1
    p_a = basket[char1].mean()

    # Probability of character 2
    p_b = basket[char2].mean()

    # Probability of both characters
    p_ab = (
        basket[char1].astype(bool) &
        basket[char2].astype(bool)
    ).mean()

    # Lift
    lift = p_ab / (p_a * p_b)

    return lift


pair_itemsets["lift"] = pair_itemsets["itemsets"].apply(
    calculate_lift
)


# ==========================================
# 5. Create readable character names
# ==========================================

pair_itemsets["Character_1"] = pair_itemsets[
    "itemsets"
].apply(lambda x: sorted(x)[0])

pair_itemsets["Character_2"] = pair_itemsets[
    "itemsets"
].apply(lambda x: sorted(x)[1])


# ==========================================
# 6. Final table
# ==========================================

pair_results = pair_itemsets[
    [
        "Character_1",
        "Character_2",
        "Comment_Count",
        "support",
        "lift"
    ]
].sort_values(
    "lift",
    ascending=False
)


pair_results.reset_index(drop=True, inplace=True)

pair_results

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/mlxtend/frequent_patterns/fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

       Character_1      Character_2  Comment_Count   support       lift
0         Frenchie           Kimiko             93  0.017929  10.209333
1           Hughie        Starlight            160  0.030846   5.597432
2         Frenchie           Hughie             60  0.011567   4.845777
3         Frenchie        Starlight             54  0.010411   3.961782
4          A-Train        Starlight             50  0.009639   3.844045
5           Kimiko             Ryan             63  0.012146   3.842222
6           Kimiko        Starlight             80  0.015423   3.804180
7           Hughie           Kimiko             72  0.013881   3.768937
8             Ryan      Soldier Boy             67  0.012917   3.765415
9        Starlight         The Deep             76  0.014652   3.738591
10   Billy Butcher      Sister Sage             61  0.011760   3.435249
11   Billy Butcher             Ryan            161  0.031039   3.425237
12   Billy Butcher    Mother's Milk             54  0.010411   3.174419
13   Billy Butcher         Frenchie             79  0.015230   3.025271
14            Ryan        Starlight             73  0.014074   2.975413
15   Billy Butcher           Hughie            161  0.031039   2.939917
16          Hughie             Ryan             59  0.011375   2.647230
17   Billy Butcher           Kimiko            106  0.020436   2.630979
18  Ashley Barrett    Billy Butcher             53  0.010218   2.573784
19      Homelander      Soldier Boy            157  0.030268   2.488256
20      Homelander             Ryan            166  0.032003   2.447150
21      Homelander      Sister Sage             62  0.011953   2.419401
22   Billy Butcher  Victoria Neuman             62  0.011953   2.334248
23   Billy Butcher        Starlight            133  0.025641   2.206203
24         A-Train    Billy Butcher             54  0.010411   2.166968
25   Billy Butcher      Soldier Boy             93  0.017929   2.127113
26      Homelander      Queen Maeve             59  0.011375   2.091432
27   Billy Butcher       Homelander            335  0.064585   2.009865
28  Ashley Barrett       Homelander             59  0.011375   1.985345
29      Homelander         The Deep            111  0.021400   1.974902
30         A-Train       Homelander             68  0.013110   1.890843
31      Black Noir       Homelander             67  0.012917   1.874260
32   Billy Butcher         The Deep             68  0.013110   1.745998
33      Homelander           Kimiko            100  0.019279   1.719885
34      Homelander       Stormfront             91  0.017544   1.710833
35        Frenchie       Homelander             61  0.011760   1.618657
36      Homelander        Starlight            134  0.025834   1.540233
37      Homelander           Hughie            113  0.021785   1.429801

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)